### ISSUE TITLE
Retryable error: unable to build kubernetes objects from release manifest

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/terraform-aws-eks#10]
A recent workflow run resulted in the following error that should be added to the retryable errors list

<img width="900" alt="image" src="https://github.com/defenseunicorns/terraform-aws-uds-eks/assets/16000938/7ed99cbf-d460-4e9a-a3b6-b993775a571e">

**Comment by zack-is-cool** [comment]
They refactored the aws eks blueprints repo 
https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1421#issuecomment-1622106392
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/kubernetes-addons/helm-addon/main.tf

I think we need to use
https://github.com/aws-ia/terraform-aws-eks-blueprints-addons

docs:
https://aws-ia.github.io/terraform-aws-eks-blueprints-addons/main/

**Comment by zack-is-cool** [comment]
I believe this is not relevant anymore as we've moved kubernetes api touching out of our pipelines. No more sshuttle specifically.
