### ISSUE TITLE
Switch Metrics Server to Iron Bank image

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/terraform-aws-eks#94]
### Description

In accordance with our ATO documentation, all software must source from Iron Bank or other approved application sources. Currently, the metrics server is pulled from the upstream registry.

The pattern for all other Iron Bank images used in our deployments is handled via zarf for both resiliency and production of software artifacts. 

### Use Case

In order to be in compliance with the ATO, we will either need to accredit the upstream metrics server ourself or leverage the one in IB.

### Impact

We are not in compliance with our ATO and have no way to evaluate supply chain risks associated with upstream images.

### Completion

- [ ] The change has been peer reviewed
- [ ] Automated tests have been written and/or updated, and are passing
- [ ] Documentation has been written and/or updated 

### Additional Context

Something to keep in mind during solutioning this problem is the desire for EKS to be airgap enabled for future efforts (i.e. what we implement here may help inform a needed future iteration in a IL6 cloud).

**Comment by zack-is-cool** [comment]
We have create a zarf package (and UDS bundle) pattern for this here:

https://github.com/orgs/defenseunicorns/packages?repo_name=narwhal-delivery-zarf-package-eks-addons
https://github.com/defenseunicorns/narwhal-delivery-zarf-package-eks-addons/tree/main/packages/metrics-server

The pattern we've chose to deploy IB images is through zarf packages/uds bundles. If there are resources that would normally be staged by the upstream blueprints module, parameters for those are staged in SSM for consumption by the zarf packages that will use them as helm values.
see:
https://github.com/defenseunicorns/terraform-aws-eks/blob/main/eks-addons.tf#L113-L143

aws NTH example:
https://github.com/defenseunicorns/narwhal-delivery-zarf-package-eks-addons/blob/main/packages/aws-node-termination-handler/zarf.yaml#L44-L70

**Comment by zack-is-cool** [comment]
I believe this has been solved by the implementation of using zarf packages to handle k8s api related things.
Additionally, for non-airgapped scenarios users can pass in arbitrary helm chart values if necessary via the `metrics_server` variable
https://github.com/defenseunicorns/terraform-aws-eks/blob/d59054ee03330d5816ea3413e4a48c567d5ed07f/variables.tf#L254-L258
https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/main/main.tf#L3153-L3207
